# Nixpacks configuration for Coolify
# This file explicitly overrides Nixpacks auto-detection
# and forces it to use Node.js instead of Deno

[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["npm ci --only=production"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx serve -s dist -l 3000"

# Explicitly disable Deno detection
[detectors]
deno = false
